export const REDU_LOAD_PROJECTS="REDU_LOAD_PROJECTS"
export const REDU_SAVE_PROJECTS="REDU_SAVE_PROJECTS"
export const REDU_UPDATE_PROJECTS="REDU_UPDATE_PROJECTS"
export const REDU_DELETE_PROJECTS="REDU_DELETE_PROJECTS"